name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copying source code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t main:v2 .

      - name: Image verification
        run: docker images