name: Sample pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: echo "Building application"

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: echo "Running tests"