name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Copying source code
        uses: actions/Checkout@v4

      - name: Docker image build
        run: docker build -t my-app .
      
      - name: Image verification
        run: docker images 